### ISSUE TITLE
Permission denied trying to upgrade to 0.4.0

### ISSUE THREAD

**Issue by gabochi** [pndmix/atom-language-pdmsg#3]
**I ran Atom with sudo but it gives me this error anyway:**

Updating to “language-rampcode@0.4.0” failed.Hide output…

> tree-sitter-rampcode@0.6.1 install /tmp/apm-install-dir-1191118-4087-ftvn9u.amtut/node_modules/language-rampcode/node_modules/tree-sitter-rampcode
> prebuild-install || node-gyp rebuild

sh: 1: prebuild-install: Permission denied
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/share/atom/resources/app/apm/bin/node',
gyp verb cli   '/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /usr/share/atom/resources/app/apm/bin/python-interceptor.sh /usr/share/atom/resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/usr/share/atom/resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "2.7.15+\n"
gyp sill stripping "+" sign(s) from version 
gyp verb get node dir compiling against --target node version: 2.0.18
gyp verb command install [ '2.0.18' ]
gyp verb install input version string "2.0.18"
gyp verb install installing version: iojs-2.0.18
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-2.0.18
gyp verb build dir attempting to create "build" dir: /tmp/apm-install-dir-1191118-4087-ftvn9u.amtut/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/tmp/apm-install-dir-1191118-4087-ftvn9u.amtut/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build'
gyp ERR! System Linux 4.15.0-72-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-1191118-4087-ftvn9u.amtut/node_modules/language-rampcode/node_modules/tree-sitter-rampcode
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1191118-4087-ftvn9u.amtut/package.json'
npm WARN apm-install-dir-1191118-4087-ftvn9u.amtut No description
npm WARN apm-install-dir-1191118-4087-ftvn9u.amtut No repository field.
npm WARN apm-install-dir-1191118-4087-ftvn9u.amtut No README data
npm WARN apm-install-dir-1191118-4087-ftvn9u.amtut No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-rampcode@0.6.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-rampcode@0.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dvinazza/.atom/.apm/_logs/2019-12-18T16_09_20_258Z-debug.log

**Comment by pndmix** [comment]
Thanks @gabochi , please try again without sudo.

**Comment by gabochi** [comment]
I get an error too, that's why I tried with sudo

```
Updating to “language-rampcode@0.4.0” failed.Hide output…

> tree-sitter-rampcode@0.6.1 install /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode
> prebuild-install || node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build'
make: Leaving directory '/tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build'

sh: 1: prebuild-install: Permission denied
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/share/atom/resources/app/apm/bin/node',
gyp verb cli   '/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.4.0
gyp info using node@8.9.3 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "/usr/share/atom/resources/app/apm/bin/python-interceptor.sh" in the PATH
gyp verb `which` succeeded /usr/share/atom/resources/app/apm/bin/python-interceptor.sh /usr/share/atom/resources/app/apm/bin/python-interceptor.sh
gyp verb check python version `/usr/share/atom/resources/app/apm/bin/python-interceptor.sh -c "import platform; print(platform.python_version());"` returned: "2.7.15+\n"
gyp sill stripping "+" sign(s) from version 
gyp verb get node dir compiling against --target node version: 2.0.18
gyp verb command install [ '2.0.18' ]
gyp verb install input version string "2.0.18"
gyp verb install installing version: iojs-2.0.18
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: iojs-2.0.18
gyp verb build dir attempting to create "build" dir: /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build
gyp verb build dir "build" dir needed to be created? /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build
gyp verb build/config.gypi creating config file
gyp sill build/config.gypi { target_defaults: 
gyp sill build/config.gypi    { cflags: [],
gyp sill build/config.gypi      default_configuration: 'Release',
gyp sill build/config.gypi      defines: [],
gyp sill build/config.gypi      include_dirs: [],
gyp sill build/config.gypi      libraries: [] },
gyp sill build/config.gypi   variables: 
gyp sill build/config.gypi    { asan: 0,
gyp sill build/config.gypi      coverage: false,
gyp sill build/config.gypi      debug_devtools: 'node',
gyp sill build/config.gypi      debug_http2: false,
gyp sill build/config.gypi      debug_nghttp2: false,
gyp sill build/config.gypi      force_dynamic_crt: 0,
gyp sill build/config.gypi      gas_version: '2.23',
gyp sill build/config.gypi      host_arch: 'x64',
gyp sill build/config.gypi      icu_data_file: 'icudt59l.dat',
gyp sill build/config.gypi      icu_data_in: '../../deps/icu-small/source/data/in/icudt59l.dat',
gyp sill build/config.gypi      icu_endianness: 'l',
gyp sill build/config.gypi      icu_gyp_path: 'tools/icu/icu-generic.gyp',
gyp sill build/config.gypi      icu_locales: 'en,root',
gyp sill build/config.gypi      icu_path: 'deps/icu-small',
gyp sill build/config.gypi      icu_small: true,
gyp sill build/config.gypi      icu_ver_major: '59',
gyp sill build/config.gypi      node_byteorder: 'little',
gyp sill build/config.gypi      node_enable_d8: false,
gyp sill build/config.gypi      node_enable_v8_vtunejit: false,
gyp sill build/config.gypi      node_install_npm: true,
gyp sill build/config.gypi      node_module_version: 57,
gyp sill build/config.gypi      node_no_browser_globals: false,
gyp sill build/config.gypi      node_prefix: '/',
gyp sill build/config.gypi      node_release_urlbase: 'https://nodejs.org/download/release/',
gyp sill build/config.gypi      node_shared: false,
gyp sill build/config.gypi      node_shared_cares: false,
gyp sill build/config.gypi      node_shared_http_parser: false,
gyp sill build/config.gypi      node_shared_libuv: false,
gyp sill build/config.gypi      node_shared_openssl: false,
gyp sill build/config.gypi      node_shared_zlib: false,
gyp sill build/config.gypi      node_tag: '',
gyp sill build/config.gypi      node_use_bundled_v8: true,
gyp sill build/config.gypi      node_use_dtrace: false,
gyp sill build/config.gypi      node_use_etw: false,
gyp sill build/config.gypi      node_use_lttng: false,
gyp sill build/config.gypi      node_use_openssl: true,
gyp sill build/config.gypi      node_use_perfctr: false,
gyp sill build/config.gypi      node_use_v8_platform: true,
gyp sill build/config.gypi      node_without_node_options: false,
gyp sill build/config.gypi      openssl_fips: '',
gyp sill build/config.gypi      openssl_no_asm: 0,
gyp sill build/config.gypi      shlib_suffix: 'so.57',
gyp sill build/config.gypi      target_arch: 'x64',
gyp sill build/config.gypi      uv_parent_path: '/deps/uv/',
gyp sill build/config.gypi      uv_use_dtrace: false,
gyp sill build/config.gypi      v8_enable_gdbjit: 0,
gyp sill build/config.gypi      v8_enable_i18n_support: 1,
gyp sill build/config.gypi      v8_enable_inspector: 1,
gyp sill build/config.gypi      v8_no_strict_aliasing: 1,
gyp sill build/config.gypi      v8_optimized_debug: 0,
gyp sill build/config.gypi      v8_promise_internal_field_count: 1,
gyp sill build/config.gypi      v8_random_seed: 0,
gyp sill build/config.gypi      v8_trace_maps: 0,
gyp sill build/config.gypi      v8_use_snapshot: true,
gyp sill build/config.gypi      want_separate_host_toolset: 0,
gyp sill build/config.gypi      nodedir: '/home/dvinazza/.atom/.node-gyp/.node-gyp/iojs-2.0.18',
gyp sill build/config.gypi      copy_dev_lib: true,
gyp sill build/config.gypi      standalone_static_library: 1,
gyp sill build/config.gypi      cache_lock_stale: '60000',
gyp sill build/config.gypi      ham_it_up: '',
gyp sill build/config.gypi      legacy_bundling: '',
gyp sill build/config.gypi      sign_git_tag: '',
gyp sill build/config.gypi      user_agent: 'npm/6.2.0 node/v8.9.3 linux x64',
gyp sill build/config.gypi      always_auth: '',
gyp sill build/config.gypi      bin_links: 'true',
gyp sill build/config.gypi      key: '',
gyp sill build/config.gypi      allow_same_version: '',
gyp sill build/config.gypi      description: 'true',
gyp sill build/config.gypi      fetch_retries: '2',
gyp sill build/config.gypi      heading: 'npm',
gyp sill build/config.gypi      if_present: '',
gyp sill build/config.gypi      init_version: '1.0.0',
gyp sill build/config.gypi      user: '',
gyp sill build/config.gypi      prefer_online: '',
gyp sill build/config.gypi      force: '',
gyp sill build/config.gypi      only: '',
gyp sill build/config.gypi      read_only: '',
gyp sill build/config.gypi      cache_min: '10',
gyp sill build/config.gypi      init_license: 'ISC',
gyp sill build/config.gypi      target: '2.0.18',
gyp sill build/config.gypi      editor: 'vi',
gyp sill build/config.gypi      rollback: 'true',
gyp sill build/config.gypi      tag_version_prefix: 'v',
gyp sill build/config.gypi      userconfig: '/home/dvinazza/.atom/.apmrc',
gyp sill build/config.gypi      cache_max: 'Infinity',
gyp sill build/config.gypi      timing: '',
gyp sill build/config.gypi      engine_strict: '',
gyp sill build/config.gypi      init_author_name: '',
gyp sill build/config.gypi      init_author_url: '',
gyp sill build/config.gypi      tmp: '/tmp',
gyp sill build/config.gypi      depth: 'Infinity',
gyp sill build/config.gypi      package_lock_only: '',
gyp sill build/config.gypi      save_dev: '',
gyp sill build/config.gypi      usage: '',
gyp sill build/config.gypi      metrics_registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      progress: '',
gyp sill build/config.gypi      otp: '',
gyp sill build/config.gypi      package_lock: 'true',
gyp sill build/config.gypi      https_proxy: '',
gyp sill build/config.gypi      save_prod: '',
gyp sill build/config.gypi      audit: 'true',
gyp sill build/config.gypi      cidr: '',
gyp sill build/config.gypi      onload_script: '',
gyp sill build/config.gypi      sso_type: 'oauth',
gyp sill build/config.gypi      rebuild_bundle: 'true',
gyp sill build/config.gypi      save_bundle: '',
gyp sill build/config.gypi      shell: '/bin/bash',
gyp sill build/config.gypi      dry_run: '',
gyp sill build/config.gypi      prefix: '/usr/share/atom/resources/app/apm',
gyp sill build/config.gypi      runtime: 'electron',
gyp sill build/config.gypi      scope: '',
gyp sill build/config.gypi      browser: '',
gyp sill build/config.gypi      cache_lock_wait: '10000',
gyp sill build/config.gypi      ignore_prepublish: '',
gyp sill build/config.gypi      registry: 'https://registry.npmjs.org/',
gyp sill build/config.gypi      save_optional: '',
gyp sill build/config.gypi      searchopts: '',
gyp sill build/config.gypi      versions: '',
gyp sill build/config.gypi      cache: '/home/dvinazza/.atom/.apm',
gyp sill build/config.gypi      send_metrics: '',
gyp sill build/config.gypi      global_style: 'true',
gyp sill build/config.gypi      ignore_scripts: '',
gyp sill build/config.gypi      version: '',
gyp sill build/config.gypi      node_gyp: '/usr/share/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp',
gyp sill build/config.gypi      local_address: '',
gyp sill build/config.gypi      viewer: 'man',
gyp sill build/config.gypi      prefer_offline: '',
gyp sill build/config.gypi      color: 'true',
gyp sill build/config.gypi      no_proxy: '',
gyp sill build/config.gypi      sign_git_commit: '',
gyp sill build/config.gypi      fetch_retry_mintimeout: '10000',
gyp sill build/config.gypi      maxsockets: '50',
gyp sill build/config.gypi      offline: '',
gyp sill build/config.gypi      sso_poll_frequency: '500',
gyp sill build/config.gypi      umask: '0002',
gyp sill build/config.gypi      fetch_retry_maxtimeout: '60000',
gyp sill build/config.gypi      logs_max: '10',
gyp sill build/config.gypi      message: '%s',
gyp sill build/config.gypi      ca: '',
gyp sill build/config.gypi      cert: '',
gyp sill build/config.gypi      global: '',
gyp sill build/config.gypi      link: '',
gyp sill build/config.gypi      access: '',
gyp sill build/config.gypi      also: '',
gyp sill build/config.gypi      save: 'true',
gyp sill build/config.gypi      unicode: 'true',
gyp sill build/config.gypi      long: '',
gyp sill build/config.gypi      production: 'true',
gyp sill build/config.gypi      searchlimit: '20',
gyp sill build/config.gypi      unsafe_perm: 'true',
gyp sill build/config.gypi      update_notifier: 'true',
gyp sill build/config.gypi      auth_type: 'legacy',
gyp sill build/config.gypi      node_version: '8.9.3',
gyp sill build/config.gypi      tag: 'latest',
gyp sill build/config.gypi      git_tag_version: 'true',
gyp sill build/config.gypi      commit_hooks: 'true',
gyp sill build/config.gypi      script_shell: '',
gyp sill build/config.gypi      shrinkwrap: 'true',
gyp sill build/config.gypi      fetch_retry_factor: '10',
gyp sill build/config.gypi      save_exact: '',
gyp sill build/config.gypi      strict_ssl: 'true',
gyp sill build/config.gypi      globalconfig: '/home/dvinazza/.atom/.apm/.apmrc',
gyp sill build/config.gypi      dev: '',
gyp sill build/config.gypi      init_module: '/home/dvinazza/.atom/.node-gyp/.npm-init.js',
gyp sill build/config.gypi      parseable: '',
gyp sill build/config.gypi      globalignorefile: '/usr/share/atom/resources/app/apm/etc/npmignore',
gyp sill build/config.gypi      cache_lock_retries: '10',
gyp sill build/config.gypi      searchstaleness: '900',
gyp sill build/config.gypi      node_options: '',
gyp sill build/config.gypi      save_prefix: '^',
gyp sill build/config.gypi      scripts_prepend_node_path: 'warn-only',
gyp sill build/config.gypi      group: '1000',
gyp sill build/config.gypi      init_author_email: '',
gyp sill build/config.gypi      searchexclude: '',
gyp sill build/config.gypi      dist_url: 'https://atom.io/download/electron',
gyp sill build/config.gypi      git: 'git',
gyp sill build/config.gypi      optional: 'true',
gyp sill build/config.gypi      json: '' } }
gyp verb build/config.gypi writing out config file: /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build/config.gypi
gyp verb config.gypi checking for gypi file: /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/config.gypi
gyp verb common.gypi checking for gypi file: /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/share/atom/resources/app/apm/bin/python-interceptor.sh
gyp info spawn args [ '/usr/share/atom/resources/app/apm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/atom/resources/app/apm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/dvinazza/.atom/.node-gyp/.node-gyp/iojs-2.0.18/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/dvinazza/.atom/.node-gyp/.node-gyp/iojs-2.0.18',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/atom/resources/app/apm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/dvinazza/.atom/.node-gyp/.node-gyp/iojs-2.0.18
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: *** No rule to make target 'Release/obj.target/tree_sitter_rampcode_binding/src/parser.o', needed by 'Release/obj.target/tree_sitter_rampcode_binding.node'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-72-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/node_modules/language-rampcode/node_modules/tree-sitter-rampcode
gyp ERR! node -v v8.9.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-12004-3728-1qzqff0.4wkf/package.json'
npm WARN apm-install-dir-12004-3728-1qzqff0.4wkf No description
npm WARN apm-install-dir-12004-3728-1qzqff0.4wkf No repository field.
npm WARN apm-install-dir-12004-3728-1qzqff0.4wkf No README data
npm WARN apm-install-dir-12004-3728-1qzqff0.4wkf No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-rampcode@0.6.1 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-rampcode@0.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

**Comment by gabochi** [comment]
I also tried uninstalling the previous version and didn't work either

**Comment by pndmix** [comment]
Hi, I tried it on ubuntu and succeeded when I installed Atom via .deb file.

Reference:
* similar issue in other package https://github.com/platformio/platformio-atom-ide-terminal/issues/795
* official install manual https://flight-manual.atom.io/getting-started/sections/installing-atom/#platform-linux
~~~
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
$ atom --version
Atom    : 1.42.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
~~~

**Comment by pndmix** [comment]
Release new version. https://github.com/pndmix/atom-pdmsg
